### ISSUE TITLE
`publish_new_items` field in `items` table

### ISSUE THREAD

**Issue by psucodervn** [vdlp/oc-rssfetcher-plugin#1]
https://github.com/vdlp/oc-rssfetcher-plugin/blob/e8bb4688a35d6125c6b310e401adb1e8a808b5c6/updates/20180718_0002_create_items_table.php#L37

This field should be in the `sources` table, isn't it?

**Comment by adrenth** [comment]
Thank you! This will be fixed in the next release (1.0.2).
