### ISSUE TITLE
Issue when installing for the first time

### ISSUE THREAD

**Issue by HitArrowLegend** [vdlp/oc-rssfetcher-plugin#11]
Tried to install the plugin but got this error

Update failed
"SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'vdlp_rssfetcher_sources' already exists (SQL: create table `vdlp_rssfetcher_sources` (`id` int unsigned not null auto_increment primary key, `name` varchar(40) null, `description` mediumtext null, `source_url` mediumtext not null, `max_items` smallint not null, `fetched_at` datetime null, `is_enabled` tinyint(1) not null default '0', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate utf8mb4_unicode_ci engine = InnoDB)" on line 664 of /home/episode1/allthings-prog/v1/vendor/laravel/framework/src/Illuminate/Database/Connection.php

**Comment by adrenth** [comment]
How did you try to install this plugin? Using the back-end?

I cannot reproduce this error on a fresh install of October CMS (latest build).

Probably you have installed this plugin earlier?

Try this command on the commandline:

```
php artisan plugin:refresh Vdlp.RssFetcher
```

Or remove the database tables manually:
- vdlp_rssfetcher_items
- vdlp_rssfetcher_sources
- vdlp_rssfetcher_feeds

Or remove the plugin using this command:

```
php artisan plugin:remove Vdlp.RssFetcher
```

**Comment by HitArrowLegend** [comment]
I tried using the backend, as usual. SOmehow I got a first error that I forgot to save up. When trying to reinstall after that, thisis what I get. I'll check my db do remove those tables.

edit: I did as you said, removed the tables, removed the files and redownloaded it. This is the first error I had but couldn't remember:  

Update failed
"Type error: Return value of Vdlp\RssFetcher\Updates\CreateSourcesTable::up() must be an instance of Vdlp\RssFetcher\Updates\void, none returned" on line 31 of /home/episode1/allthings-prog/v1/plugins/vdlp/rssfetcher/updates/20180718_0001_create_sources_table.php

**Comment by adrenth** [comment]
This is because you're running an unsupported PHP version. 
The minimal required PHP version is 7.1.

**Comment by HitArrowLegend** [comment]
I'm using php7.3

**Comment by HitArrowLegend** [comment]
nevermind, I got it fixed somehow. Cpanel was saying 7.3 but I installed it again and it worked
