### ISSUE TITLE
Error: Class 'October\Rain\Support\Facades\Event' not found

### ISSUE THREAD

**Issue by artistro08** [vdlp/oc-rssfetcher-plugin#12]
For some reason, It is not detecting the Event Emitter and I'm not sure why. Everytime I try and fetch sources, I get this error code. 

Commenting out the lines associated in the plugin makes it work again.

**Comment by adrenth** [comment]
Hi @artistro08, thanks for reporting this issue. I fixed this issue in `3.0.3`. Please let me know if this fix resolves your issue.

**Comment by adrenth** [comment]
Seems to be an issue with the lastest `october/rain` library. 

This is caused at the `aliases.php` script, which is located here: `modules/system/aliases.php`

I have reported the issue.

**Comment by artistro08** [comment]
I wasn't able to get the update, but now I see why. Thank you.
