### ISSUE TITLE
Stylesheet Location

### ISSUE THREAD

**Issue by nvandendries1984** [vdlp/oc-rssfetcher-plugin#14]
Hello, 

I want to style-up the RSS output on the Front page of my website,
But I cant find the stylesheet for it.

Gr Niels
TheDailyGeek.nl

**Comment by adrenth** [comment]
That’s correct. That is not the responsibility of this plugin. You should create the styles yourself. 

The components shipped with this plugin are examples on how to output the items. Feel free to override the partials and create your own stylesheet for it.

**Comment by nvandendries1984** [comment]
@adrenth Hell yeah, Thx man
