### ISSUE TITLE
Connection to Soap with authentication?

### ISSUE THREAD

**Issue by RodrigoGalter** [vdlp/oc-rssfetcher-plugin#4]
Is there a possibility to connect in an RSS via SOAP with authentication?

**Comment by adrenth** [comment]
Sure you can, you can extend the controller (see: https://github.com/vdlp/oc-rssfetcher-plugin/blob/master/http/controllers/FeedController.php). Or write yourself a controller which supports Soap Authentication.

This is not a feature we want in this plugin.
