### ISSUE TITLE
empty description from fetched items

### ISSUE THREAD

**Issue by quailegg** [vdlp/oc-rssfetcher-plugin#5]
i try to fetch items from the feed url "https://www.vdh.de/home/?type=101" - Verband für das Deutsche Hundewesen

items are successfully imported but the description attribute is empty

**Comment by jrosell** [comment]
I would expect to be able to configure strip_tags is aplied or not:

classes/RssFetcher.php
'description' => strip_tags($item->getContent()),

**Comment by adrenth** [comment]
This issue is addressed in v2.0.0. 

You can now implement events to filter the contents of a feed.
