### ISSUE TITLE
Allowed memory size exhausted on Cron Job 

### ISSUE THREAD

**Issue by Ultrapraise** [vdlp/oc-rssfetcher-plugin#6]
Cron jobs were running without any issue but suddenly stopped and started giving this error log:

PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 147456 bytes) in /var/www/html/yans-news/vendor/phpunit/phpunit/src/Framework/Assert.php on line 1942

I doubled the memory size (php.ini) and the error hasn't gone and the Cron hasn't resumed working.

What could be causing the issue. I feel the command is creating an Infinite loop or something.

**Comment by adrenth** [comment]
That totally depends on what kind of RSS feed.

This could also be an error unrelated to te plugin. If you are still experiencing this issue, please provide us with a full stack trace.
